option(OMP_ENABLE "Multi-threading using OpenMP (up to v2.0 on Windows)" OFF)
option(OMP_IMAGEWORKER "Multi-thread the image worker process independently of the decode thread" OFF)
option(OMP_MANUAL_THREADS "Use Hard-coded amount of threads." OFF)

if(OMP_ENABLE)
    FIND_PACKAGE(OpenMP REQUIRED QUIET) # cmake-provided module
    if (OPENMP_FOUND)
        set(OMP_ENABLE ON CACHE "" BOOL)
        set(OpenMP_CXX_FLAGS "${OpenMP_CXX_FLAGS} /DOMP_ENABLE")
        if(OMP_IMAGEWORKER)
            set(OpenMP_CXX_FLAGS "${OpenMP_CXX_FLAGS} /DOMP_IMAGEWORKER")
        endif()
        if(OMP_MANUAL_THREADS)
            set(OpenMP_CXX_FLAGS "${OpenMP_CXX_FLAGS} /DOMP_MANUAL_THREADS")
        endif()
        if(WINDOWS)
            if(WORD_SIZE EQUAL 64)
                set(OPENMP_LIBRARY "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\lib\\amd64\\vcomp.lib")
            else()
                set(OPENMP_LIBRARY "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\lib\\vcomp.lib")
            endif()
        endif()
        #TODO: Linx and darwin
    else()
        unset(OMP_ENABLE)
        unset(OMP_IMAGEWORKER)
        unset(OMP_MANUAL_THREADS)
    endif()
endif()
