
if(OMP_ENABLE)
    find_package(OpenMP)
    if (OPENMP_FOUND)
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
        set(OpenMP_Support ON)
        if(OMP_IMAGEWORKER)
            set(OpenMP_ImageWorker ON)
        endif()
        if(OMP_MANUAL_THREADS)
            set(OpenMP_ManualThreads ON)
        endif()
    else()
        set(OMP_ENABLE OFF CACHE BOOL "" FORCE)
        unset(OpenMP_Support)
        unset(OpenMP_ImageWorker)
        unset(OpenMP_ManualThreads)
    endif()
endif()
