if(NOT DEFINED ${CMAKE_CURRENT_LIST_FILE}_INCLUDED)
set(${CMAKE_CURRENT_LIST_FILE}_INCLUDED "YES")

set(PVDATA_SYSTEM TRUE CACHE BOOL "Master setting to compile PVDAta into the viewer" FORCE)
option(PVDATA_UUID_LOCKDOWN "Lock down the viewer to a specific user" OFF)
set(PVDATA_UUID_LOCKTO "${PVDATA_UUID_LOCKTO}" CACHE STRING "UUID to lock down to" FORCE)

if(PVDATA_SYSTEM)
  add_definitions("-DPVDATA_SYSTEM")
  if(PVDATA_UUID_LOCKDOWN)
    add_definitions("-DPVDATA_UUID_LOCKDOWN -DPVDATA_UUID_LOCKTO=${PVDATA_UUID_LOCKTO}")
  endif(PVDATA_UUID_LOCKDOWN)
else(NOT PVDATA_SYSTEM)
  add_definitions("-UPVDATA_SYSTEM -UPVDATA_UUID_LOCKTO -UPVDATA_UUID_LOCKDOWN")
endif(PVDATA_SYSTEM)

endif(NOT DEFINED ${CMAKE_CURRENT_LIST_FILE}_INCLUDED)
